export const LOGIN_LOGIN_CHANGE = 'LOGIN_LOGIN_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';

export const REGISTER_LOGIN_CHANGE = 'REGISTER_LOGIN_CHANGE';
export const REGISTER_PASSWORD_CHANGE = 'REGISTER_PASSWORD_CHANGE';
export const REGISTER_NAME_CHANGE = 'REGISTER_NAME_CHANGE';
export const REGISTER_MAIL_CHANGE = 'REGISTER_MAIL_CHANGE';
export const REGISTER_USER_DATA_AGREEENT_CHANGE = 'REGISTER_USER_DATA_AGREEENT_CHANGE';
export const REGISTER_USER_OFFER_AGREEMENT_CHANGE = 'REGISTER_USER_OFFER_AGREEMENT_CHANGE';

export const MAIN_SET_USER_DATA = 'MAIN_SET_USER_DATA';
export const MAIN_SET_USER_VIDEO_LIST = 'MAIN_SET_USER_VIDEO_LIST';

export const NEW_VIDEO_SET_VIDEO_DATA = 'NEW_VIDEO_SET_VIDEO_DATA';

export const SEND_ADDED_VIDEO_NAME = 'SEND_ADDED_VIDEO_NAME';
export const SEND_ADDED_VIDEO_DESCRIPTION = 'SEND_ADDED_VIDEO_DESCRIPTION';
export const SEND_ADDED_VIDEO_FILM_NAME = 'SEND_ADDED_VIDEO_FILM_NAME';
export const SEND_ADDED_VIDEO_EFIR_DATE = 'SEND_ADDED_VIDEO_EFIR_DATE';
export const SEND_ADDED_VIDEO_COUNTRY_CITY_FROM = 'SEND_ADDED_VIDEO_COUNTRY_CITY_FROM';
export const SEND_ADDED_VIDEO_ACTIVITY_TYPE = 'SEND_ADDED_VIDEO_ACTIVITY_TYPE';
export const SEND_ADDED_VIDEO_FORM_EMPTY = 'SEND_ADDED_VIDEO_FORM_EMPTY';
